CREATE TABLE aluno (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome TEXT,
	nota SMALLINT,
	cpf VARCHAR(14),
	data_nascimento DATE,
	email TEXT,
	instituicao_id BIGINT REFERENCES public.instituicao(id),
	created_at TIMESTAMPTZ DEFAULT now(),
	updated_at TIMESTAMPTZ DEFAULT now(),
	deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE professor (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome TEXT,
	curso TEXT,
	materia JSONB,
	email TEXT,
	instituicao_id BIGINT REFERENCES public.instituicao(id),
	created_at TIMESTAMPTZ DEFAULT now(),
	updated_at TIMESTAMPTZ DEFAULT now(),
	deleted_at TIMESTAMPTZ DEFAULT NULL
);


CREATE TABLE instituicao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tipo TEXT,
	endereco JSONB,
	created_at TIMESTAMPTZ DEFAULT now(),
	updated_at TIMESTAMPTZ DEFAULT now(),
	deleted_at TIMESTAMPTZ DEFAULT NULL
);

